<?php
/**
 * ePoster v1
 *
 * @author Cindy Chusseau
 * @copyright EUROPA ORGANISATION ©2009
 * @version 1.0
 */

/**
 * listecompleteView
 * @package Views
 */
?>

<?php if($this->choix == false){?>
<div id="boxRecherche">
    <?php echo $this->form; ?>
    <div id="resultatRecherche"></div><!-- div contenant les résultats de la recherche dynamique -->
</div>
<?php } ?>

<?php if($this->formatPage == false){?>
<div id="listeAbstract">
<?php } ?>
	<ul>
		<?php if(count($this->resume)>0){
			$i=0;
			foreach($this->resume as $key=>$abstract){
				if($i%2==0){ ?>
					<li class="lineColor" onclick="$(location).attr('href','<?php echo $this->baseUrl; ?>/index/slide/abstract/<?php echo $key; ?>');" style="cursor:pointer;" onmouseover="$(this).addClass('liHover')" onmouseout="$(this).removeClass('liHover')">
				<?php }else{ ?>
					<li onclick="$(location).attr('href','<?php echo $this->baseUrl; ?>/index/slide/abstract/<?php echo $key; ?>');" style="cursor:pointer;" onmouseover="$(this).addClass('liHover')" onmouseout="$(this).removeClass('liHover')">
				<?php }
				$i++
				?>
        			<div class="abstract">
           				<h3>
           					<span class="vignette"><?php echo $abstract['idDefinitive']; ?></span>&nbsp;<?php echo html_entity_decode($abstract['title']); ?></h3>
            			<p>
            				<?php 
            				$j=1;
            				foreach($abstract['author'] as $author){  
            					echo $author['initials'].' '.$author['lastName'];
            					if($j < count($abstract['author'])) echo ' - '; 
            					$j++;
            				} ?>
            			</p>
						<p>
            				<span><img src="<?php echo $this->baseUrl; ?>/public/images/btn-category.png" alt="" style="vertical-align:middle;" /> <?= $abstract['name']; ?> </span>
            			</p>
            			<div id="infoAbstract">
							<div id="infocentre">
								<span><img src="<?php echo $this->baseUrl; ?>/public/images/btn-preview.png" alt="" style="vertical-align:middle;" /> <?php echo $abstract['viewSlide'].' '.$this->translate("vue(s)"); ?></span>
								<?php if(Zend_Registry::get('config')->option->notation == true){ 
									if(isset($this->note[$key]['slide'])){
										$note = $this->note[$key]['slide']*135/5;
									}else{
										$note = 0;
									}
									$notation = 'width:'.$note.'px';
									?>
									<div id="fake-stars-off" class="stars-off">
										<div id="fake-stars-on" class="stars-on" style="<?php echo $notation; ?>"></div>
									</div>
								<?php } ?>
							</div>
							<div id="inforight">
							
					</div>
						</div>
        			</div>
        			<div class="abstract-btns" style="text-align:center;">
						<?php if($abstract['deleted'] == 0){ ?>
            			<a href="<?php echo $this->baseUrl; ?>/admin/supprimerabstract/abstract/<?php echo $key; ?>" title="Supprimer">
						<img height="30" src="<?php echo $this->baseUrl; ?>/public/images/deleted_icon.png"><br/>
               				<span>Désactiver</span>
           				</a>
						<?php }else{ ?>
						<a href="<?php echo $this->baseUrl; ?>/admin/activerabstract/abstract/<?php echo $key; ?>" title="Activer">
						<img height="30" src="<?php echo $this->baseUrl; ?>/public/images/check_icon.png"><br/>
               				<span>Activer</span>
           				</a>
						<?php } ?>
       			 	</div>
				</li>
			<?php }
		}else{ ?>	
			<li class="lineColor">
				<div class="abstract" style="text-align:center;">
					<h3><?php echo $this->translate("Aucun résultat"); ?></h3>
				</div>
			</li>	
		<?php } ?>
	</ul>
<?php if($this->formatPage == false){?>
</div>
<?php } ?>