<?php
/**
 * ePoster v1
 *
 * @author Cindy Chusseau
 * @copyright EUROPA ORGANISATION ©2010
 * @version 1.0
 */

/**
 * commenter
 * @package Views
 */
 
?> 


	<div id="close">
		<a onclick="deleteOverlay();"><img src="<?php echo $this->baseUrl; ?>/public/images/icon-close-white.png" alt="<?php echo $this->translate("Fermer"); ?>" title="<?php echo $this->translate("Fermer"); ?>" /></a>
	</div>
	
	<h2><?php echo $this->translate("Envoyer un e-mail"); ?></h2>
	<?php echo $this->form; ?>
