<?php
/**
 * ePoster v1
 *
 * @author Cindy Chusseau
 * @copyright EUROPA ORGANISATION ©2009
 * @version 1.0
 */

/**
 * listecompleteView
 * @package Views
 */
?>

<!--
<?php if($this->choix == false){?>
<div id="boxRecherche">
    <?php echo $this->form; ?>
    <div id="resultatRecherche"></div>
</div>
<?php } ?> -->

<?php if($this->formatPage == false){?>
<div id="listeAbstract">
<?php } ?>
	<ul>
		<?php if(count($this->resume)>0){
			$i=0;
			foreach($this->resume as $key=>$abstract){
				if($i%2==0){ ?>
					<li class="lineColor" onclick="$(location).attr('href','<?php echo $this->baseUrl; ?>/index/slide/abstract/<?php echo $abstract['idAbstract']; ?>');" style="cursor:pointer;" onmouseover="$(this).addClass('liHover')" onmouseout="$(this).removeClass('liHover')">
				<?php }else{ ?>
					<li onclick="$(location).attr('href','<?php echo $this->baseUrl; ?>/index/slide/abstract/<?php echo $abstract['idAbstract']; ?>');" style="cursor:pointer;" onmouseover="$(this).addClass('liHover')" onmouseout="$(this).removeClass('liHover')">
				<?php }
				$i++
				?>
        			<div class="abstract">
           				<h3>
           					<span class="vignette"><?php echo $abstract['idDefinitive']; ?></span>&nbsp;<?php echo utf8_encode($abstract['title']); ?></h3>
            			<p>
            				<?php 
            				$j=1;
            				foreach($abstract['author'] as $author){  
            					echo mb_strtoupper(html_entity_decode($author['initials'].' '.$author['lastName'], ENT_QUOTES, 'UTF-8'));
                                                
                                                if(!empty($author['city']) || !empty($author['country'])){
                                                    echo " (";
                                                    
                                                    if(!empty($author['city'])){
                                                        
                                                        echo utf8_encode(mb_strtoupper(html_entity_decode($author['city'], ENT_QUOTES)));
                                                        if(!empty($author['country'])){
                                                            echo ", ".$author['country'];
                                                        }
                                                    }else{
                                                        echo $author['country'];
                                                    }
                                                    
                                                    echo ")";
                                                }
                                                
                                                
                                                
            					if($j < count($abstract['author'])) echo ' - '; 
            					$j++;
            				} ?>
            			</p>
            			<p>
          <?php if($abstract['name'] != "NOCATEGORY"){ ?><span class="vignette"><?php echo $abstract['name']; ?> </span><?php } ?>
        			</p>
            			<div id="infoAbstract">
            				
							<div id="infocentre">
								<span><img src="<?php echo $this->baseUrl; ?>/public/images/btn-preview.png" alt="" style="vertical-align:middle;" /> <?php echo $abstract['viewSlide'].' '.$this->translate("vue(s)"); ?></span>
								<?php if(Zend_Registry::get('config')->option->notation == true){ 
									if(isset($this->note[$key]['slide'])){
										$note = $this->note[$key]['slide']*135/5;
									}else{
										$note = 0;
									}
									$notation = 'width:'.$note.'px';
									?>
									<div id="fake-stars-off" class="stars-off">
										<div id="fake-stars-on" class="stars-on" style="<?php echo $notation; ?>"></div>
									</div>
								<?php } ?>
							</div>
							<div id="inforight">
					</div>
						</div>
        			</div>
        			<div class="abstract-btns">
            			<a href="<?php echo $this->baseUrl; ?>/index/slide/abstract/<?php echo $abstract['idAbstract'] ?>" title="<?php echo $this->translate("Diaporama"); ?>" class="btn-diapo">
                			<span><?php echo $this->translate("Diaporama"); ?></span>
            			</a>
       			 	</div>
				</li>
			<?php }
		}else{ ?>	
			<li class="lineColor">
				<div class="abstract" style="text-align:center;">
					<h3><?php echo $this->translate("Aucun résultat"); ?></h3>
				</div>
			</li>	
		<?php } ?>
	</ul>
<?php if($this->formatPage == false){?>
</div>
<?php } ?>