<?php
/**
 * ePoster v1
 *
 * @author Cindy Chusseau
 * @copyright EUROPA ORGANISATION ©2009
 * @version 1.0
 */

/**
 * IndexView
 * @package Views
 */

?>
<div id="home">
	<ul>
		<li>
			<a href="<?php echo $this->baseUrl; ?>/index/keywords"><?php echo $this->translate("Liste"); ?></a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl; ?>/index/search/type/title"><?php echo $this->translate("Recherche par titre"); ?></a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl; ?>/index/search/type/author"><?php echo $this->translate("Recherche par auteur"); ?></a>
		</li>
	</ul>
</div>