<?php
/**
 * INTRANET v1
 *
 * @author Cindy Chusseau
 * @copyright EUROPA ORGANISATION ©2009
 * @version 1.0
 */

/**
 * IndexView
 * @package Views
 */

	$controller = Zend_Controller_Front::getInstance()->getRequest();
?>

<h3 class="big" align="center"><?php echo html_entity_decode($this->resume[0]->title); ?></h3>
<p align="center">
	<?php
	$i=0; 
	foreach($this->author as $author)
	{
		if($i!=0)
		{
			echo ', ';
			echo $author->firstName.' '.$author->lastName;
		}
		else
		{
			echo '<strong>'.$author->firstName.' '.$author->lastName.'</strong>';
		}
		$i++;
	}
    ?>
</p>
<h2 style="border-bottom: 1px solid black;"><?php echo $this->translate("Commentaires Diapo"); ?></h2><br />
<div id="listeAbstract">
	<ul>
	<?php
		$i = 0;
		$commentsSlide = $this->commentSlide;
		if (count($commentsSlide) < 1) {
			echo 'Il n\'y a aucun commentaire';
		} else { 
		foreach ($commentsSlide as $user) {
				if($i%2==0){
					echo '<li class="lineColor">';
				}
				else{
					echo '<li  class="line">';
				}
	
					$i++;
			echo '	<div class="abstract">
					<h3>'.$user->name.'</h3>
					<p style="border-bottom: 1px solid black;">Enregistré le <i>'.date('l jS \of F Y \à H:i ', $user->dateAdd).'</i></p>
					<hr>
					<p>
						'.$user->comment.'
					</p>
					</div>
										<div class="abstract-btns" style="text-align:center;">
            			<a href="'.$this->baseUrl.'/admin/supprimerComment/abstract/'.$user->idAbstract.'/comment/'.$user->idComment.'" title="Supprimer">
						<img height="30" src="'.$this->baseUrl.'/public/images/deleted_icon.png"><br/>
               			<span>Supprimer</span>
           				</a>
           			</div>
				</li> ';
			}
		}
	?>
	</ul>
</div>
<br />
<h2 style="border-bottom: 1px solid black;"><?php echo $this->translate("Commentaires Video"); ?></h2><br />
<div id="listeAbstract">
	<ul>
	<?php
		$commentsVideo = $this->commentVideo;
		if (count($commentsVideo) < 1) {
			echo 'Il n\'y a aucun commentaire';
		} else { 
		foreach ($commentsVideo as $user) {
				if($i%2==0){
					echo '<li class="lineColor">';
				}
				else{
					echo '<li  class="line">';
				}
	
					$i++;
			echo '	<div class="abstract">
					<h3>'.$user->name.'</h3>
					<p style="border-bottom: 1px solid black;">Enregistré le <i>'.date('l jS \of F Y \à H:i ', $user->dateAdd).'</i></p>
					<hr>
					<p>
						'.$user->comment.'
					</p>
					</div>
										<div class="abstract-btns" style="text-align:center;">
            			<a href="'.$this->baseUrl.'/admin/supprimerComment/abstract/'.$user->idAbstract.'/comment/'.$user->idComment.'" title="Supprimer">
						<img height="30" src="'.$this->baseUrl.'/public/images/deleted_icon.png"><br/>
               			<span>Supprimer</span>
           				</a>
           			</div>
				</li> ';
			}
		}
	?>
</ul>
</div>


<!--<div id="formulaire-modifier">
	<?php if($this->resume[0]->previewPassed == 1) { ?>
	<div id="btn-delete">
   		<a href="<?php echo $this->baseUrl; ?>/admin/supprimervideo/abstract/<?php echo $this->resume[0]->idPoster; ?>" title="Supprimer la vidéo" class="small-btn">
        	<span>Supprimer la vidéo</span>
   		</a>
	</div>
	<?php } ?>
	
	<?php echo $this->form; ?>
</div>-->


